"""Reaction model for the airGM Python port.

Rate expressions and stoichiometry are autogenerated in reaction_data.py from
src/reaction.cpp to preserve one-to-one mapping with C++.
"""

from __future__ import annotations

import math

from .reaction_data import PRODUCTS, RATE_EXPRESSIONS, REACTANTS

KB = 1.38064852e-23
QE = 1.6021766208e-19

COMPILED_RATE_EXPRESSIONS = {
    j: (compile(expr, f"reaction_rate_{j}", "eval"), needs_te_nonzero)
    for j, (expr, needs_te_nonzero) in RATE_EXPRESSIONS.items()
}


class Reaction:
    """Stores rate, reactants, and products for one reaction instance."""

    _MAX_NO_REACTION_SPECIES = 4

    def __init__(self) -> None:
        self.reaction_rate = 0.0
        self.reactant_species_list = [0] * (self._MAX_NO_REACTION_SPECIES + 1)
        self.product_species_list = [0] * (self._MAX_NO_REACTION_SPECIES + 1)

    def set_reaction_rate(self, j: int, t_gas: float, t_electron: float) -> None:
        te = float(t_electron)
        tg = float(t_gas)
        eps = 3.0 * KB * te / (2.0 * QE)

        compiled_expr, needs_te_nonzero = COMPILED_RATE_EXPRESSIONS[j]
        if needs_te_nonzero and te == 0.0:
            self.reaction_rate = 0.0
            return

        self.reaction_rate = float(
            eval(
                compiled_expr,
                {"__builtins__": {}},
                {"exp": math.exp, "pow": pow, "te": te, "tg": tg, "eps": eps},
            )
        )

    def set_reactant_and_product_species(self, j: int) -> None:
        reactants = REACTANTS[j]
        products = PRODUCTS[j]

        self.reactant_species_list[0] = len(reactants)
        self.product_species_list[0] = len(products)

        for i in range(1, self._MAX_NO_REACTION_SPECIES + 1):
            self.reactant_species_list[i] = 0
            self.product_species_list[i] = 0

        for i, value in enumerate(reactants, start=1):
            self.reactant_species_list[i] = value

        for i, value in enumerate(products, start=1):
            self.product_species_list[i] = value

    def return_number_of_reactants(self) -> int:
        return self.reactant_species_list[0]

    def return_number_of_products(self) -> int:
        return self.product_species_list[0]

    def return_reactant(self, item_index: int) -> int:
        return self.reactant_species_list[item_index]

    def return_product(self, item_index: int) -> int:
        return self.product_species_list[item_index]

    def return_reaction_rate(self) -> float:
        return self.reaction_rate
